### ISSUE TITLE
DUVIDA

### ISSUE THREAD

**Issue by Level0r0s** [axmachado/pacc#4]
ola.
o PACC...  gera um arquivo yacc usando um arquivo php ??

ou   gera o arquivo php usando um aquivo yacc ?:?

ou interpreta um arquivo yacc ??

nao entendi..

obrigado

**Comment by axmachado** [comment]
Olá, 0r0. 

O PACC utiliza como entrada um arquivo "parecido" com yacc e gera o parser em PHP.
